initial_node_count      =    "2"
cluster_name            = "gosonikmurod"
cpath                   =    "/root/terraform-projects/kube-cluster/civil-celerity-239622-4980eb3b6fd2.json"
project                 =    "civil-celerity-239622"
region                  =    "us-central1-a"