initial_node_count      =    "1"
cluster_name            = "gosonik"
cpath                   =    "/tmp/private_key.json"
project                 =    "astral-root-234422"
region                  =    "asia-east2"