initial_node_count      =    "2"
cluster_name            = "gosonikmurod"
cpath                   =    "/home/jozsefolah15/terraform-projects/kube-cluster/My First Project-7ded3d32f30c.json"
project                 =    "civil-celerity-239622"
region                  =    "us-central1-a"